name: Coding Style

on: [push, pull_request]

jobs:
    code-checker:
        name: Code Standard Checker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none

            - run: composer create-project janpecha/code-checker temp/code-checker ^1.0 --no-progress
            - run: temp/code-checker/code-checker --no-progress
